- name: change route53 
  route53: 
    state: present 
    zone: wread.com 
    record: www.wread.com 
    failover: PRIMARY 
    type: CNAME 
    ttl: 30 
    identifier: server1 
    private_zone: yes 
    averwrite: yes 
    value: "(( NEW_ALIAS }}" 
    wait: yes 
    health_check: "22bba738-e090-49fd-9659-9b12107406a8"
