- name: change route53 
  route53: 
    state: present 
    zone: wread.com 
    record: www.wread.com 
    failover: PRIMARY 
    type: CNAME 
    ttl: 30 
    identifier: server1 
    private_zone: yes 
    averwrite: yes 
    value: "(( NEW_ALIAS }}" 
    wait: yes 
    health_check: "7388eób5-87a4-4d5f-a638-6d125eB69349"
